name: Reusable CI

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  qodo-merge:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Run Qodo Merge
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
