name: Reusable CI

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
      command:
        required: true
        type: string
      target_repo:
        required: true
        type: string
    secrets:
      OPENAI_KEY:
        required: true

  workflow_dispatch:  # 手動実行用
    inputs:
      pr_number:
        description: 'PR番号'
        required: true
        type: string
      command:
        description: '実行するコマンド（例: /review）'
        required: true
        type: string
      target_repo:
        description: '対象リポジトリ（owner/repo）'
        required: true
        type: string

jobs:
  qodo-merge:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Qodo Merge
        uses: qodo-ai/pr-agent@main
        with:
          config-path: .pr-agent/config.json  # ← 日本語対応設定を追加
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEW_COMMAND: ${{ inputs.command }}
          GITHUB_REPOSITORY: ${{ inputs.target_repo }}
          PR_NUMBER: ${{ inputs.pr_number }}
